- name: Create node_exporter installation directory
  file:
    path: "{{ node_exporter_dir }}"
    state: directory
- name: Download node_exporter (Prometheus exporter for machine metrics)
  get_url:
    dest: "{{ node_exporter_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz" # noqa 204
    checksum: "{{ node_exporter_checksum }}"
- name: Extract node_exporter
  unarchive:
    src: "{{ node_exporter_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "{{ node_exporter_dir }}"
    remote_src: yes
    creates: "{{ node_exporter_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64"
- name: Create symbolic link to the latest node_exporter
  file:
    src: "{{ node_exporter_dir }}/node_exporter-{{ node_exporter_version }}.linux-amd64"
    dest: "{{ node_exporter_dir }}/latest"
    state: link
- name: Create node_exporter systemd system unit
  template:
    dest: /usr/local/lib/systemd/system/node_exporter.service
    src: node_exporter.service.j2
    force: yes
- name: Enable node_exporter
  systemd:
    name: node_exporter.service
    enabled: yes
    daemon_reload: yes
    state: started
